jenkins:
  systemMessage: "Hello, world! Private repo"
jobs:
      - script: >
        pipelineJob('configuration-as-code') {
            definition {
                cps {
                    sandbox()
                    script("""
                      podTemplate(label: 'mypod') {
                        node('mypod') {
                          sh "hostname"
                        }
                      }
                    """.stripIndent())
                }
            }
        }
